### ISSUE TITLE
Setup for June 8th Orchestructure Workshop

### ISSUE THREAD

**Issue by InAnimaTe** [orchestructure/presentations#48]
With such a successful [event](https://www.meetup.com/orchestructure/events/250189685/) last year, it's time to start planning the next one! This event will be an extended weekend meetup with multiple facets aimed at engaging, teaching, and bringing people together.

This issue will work similar to #33 except all discussion and checklist items will be managed here instead of in separate issues. I've left quick links to last year's version of each item for reference.

- [x] **Feedback** - @jeefy  - Lets do a poll to gauge interest and best options for engaging people. (ex #28) [Created!](https://goo.gl/forms/5oMlL1Xqkg7xkMgr2)
- [x] **Date** - @orchestructure/board - *Decided on June 8th*!
- [x] **Format** - @orchestructure/board - How do we want to spend the time. (ex #30)
- [x] **Location** - @InAnimaTe - Get an excellent location that can facilitate our needs. (ex #27)
- [x] **Food** - @mrbobbytables - Well I mean of course. (ex #29)
- [x] **Solve Recording Issues** - @jeefy - Ensure we can reliably record each session this time around. Note that live streaming isn't exactly necessary. Also, get pictures taken of the event.
- [x] **Speaker Gift and Swag** - @jeefy - Get a special speaker gift and something different for everyone!
- [x] **Meetup Page Post** - @castrojo - Get the meetup page for the event created.
- [x] **Announce** - @castrojo - Get out on Twitter, Slack, meetings, etc and announce the event

**Sessions**:
* Developer Workflow - Covers writing code and publishing a service from a developer perspective (editor, dockerfile, building, running tests, pushing, basic CI) - @swiggins83, setup by @InAnimaTe
* Automated Infrastructure - Utilizing tools to create self-driving Infrastructure with Kubernetes in AWS via EKS. - @StevenACoffman setup by @castrojo 
* Container Orchestration - Focus specifically on semantics around orchestrating a container using a scheduler like Kubernetes. Delve into Application > Container Building (Dockerfile) > Kubernetes Deployment > Lifecycle. - @jeefy, help from @mrbobbytables
* Service Mesh - Pure focus on service mesh solutions and the value add they provide for cluster administrators as well as service operators. - @bdimcheff, setup by @mrbobbytables

**Schedule**

Start | Session | Length
------------ | ------------- | -------------
10:00 | Doors Open | 1 Hour
10:45 | Introductions | 15 Minutes
11:00 | Developer Workflow - Automated Workloads | 1.5 Hours
12:30 | Lunch | 1 Hour
1:30 | Container Orchestration - Service Mesh | 1.5 Hours
3:00 | Closing Remarks | 10 Minutes

**Comment by InAnimaTe** [comment]
Two things knocked out!

**Date**: June 8th 2019!
**Format**: Same as last year, Dual-track, 4 sessions from 11am-3pm

**Comment by jeefy** [comment]
I've pinged Keith and he'll be able to take pictures for us like before.

**Comment by InAnimaTe** [comment]
@mrbobbytables @jeefy @castrojo Thoughts? Obv names will change etc..

Start | Session | Length
------------ | ------------- | -------------
10:00 | Doors Open | 1 Hour
10:45 | Introductions | 15 Minutes
11:00 | Developer Workflow and Automated Infrastructure | 1.5 Hours
12:30 | Lunch | 1 Hour
1:30 | Container Orchestration and Service Mesh with Linkerd | 1.5 Hours
3:00 | Closing Remarks | 10 Minutes

**Comment by jeefy** [comment]
Looks good. I'd want to make sure that we let people know that sessions are 1.5 hours so lunch is an hour.

Another thought: Do we want to "open doors" at 10? Gives people 50min to mingle and chat, maybe have some coffee? Then we can do a 10min intro.

**Comment by InAnimaTe** [comment]
I've updated my comment with start times and length to be more clear about what's happening when (incl doors open)

**Comment by castrojo** [comment]
Curt has a conflict that day and cannot attend but sends his regards.

**Comment by castrojo** [comment]
@mattfarina can help us out for Automated Infrastructure, so like, CI/CD, helm, what else could he cover?

**Comment by InAnimaTe** [comment]
@castrojo @mattfarina so I updated the main post with descriptions of each session.

For Automated Infra, we're thinking about the provisioning process like spawning cloud infra, having a fresh cluster provisioned, etc.. but also the ci/cd pipeline and the automated deployment it can facilitate. This could include terraform, kops, helm, jenkins, eksctl, docker-machine, etc..

**Comment by mattfarina** [comment]
@castrojo @InAnimaTe With this new description I'm not going to be the best person by a long shot. I'm an apps/workloads person rather than a provisioning cloud infra person. All my provisioning is simple API or "button pushing" these days. Other folks where I work handle the cloud provisioning.

**Comment by castrojo** [comment]
Would it make more sense to concentrate on apps/workloads instead? That would be a larger audience.

**Comment by InAnimaTe** [comment]
This is true, and since I'd really love for @mattfarina to be involved, I'm perfectly fine with a focus on application workloads incl. CI/CD etc..

@mattfarina (cc @castrojo) Give me an idea of a title+description for your ideal session. So long as it doesn't step on the others we have planned (specifically _Container Orchestration_, see main post), it should fit just fine.

**Comment by swiggins83** [comment]
@InAnimaTe what did you have in mind for the `Automated Infrastructure` part referring to for the workshop?

**Comment by InAnimaTe** [comment]
> @InAnimaTe what did you have in mind for the `Automated Infrastructure` part referring to for the workshop?

Spawning infrastructure using declarative methods with tools like Terraform, eksctl, docker-machine, etc.. See my previous [comment](https://github.com/orchestructure/presentations/issues/48#issuecomment-482117217) too.
With bringing Matt Farina in, I've changed it to Automated Workflows to reflect application deployment, CI/CD etc..

These will also get more official names from the people authoring them as we firm things up.

**Comment by StevenACoffman** [comment]
So, we can change it back to `Automated Infrastructure`, because that's more my thing. I reached out to my AWS Account rep to see if they have $25 gift certificates for people to run through a hands on experience of bringing up a cluster.

**Comment by InAnimaTe** [comment]
@StevenACoffman get me a description and ill replace the main post as well as the site.

**Comment by StevenACoffman** [comment]
@InAnimaTe How about this:
##### Self-Driving Infrastructure using Kubernetes on AWS with EKS

This workshop will provide hands on experience on setting up and running an AWS Kubernetes cluster using EKS. We will use gitops, and explore kubernetes tools to make the cluster self-driving, with automated management and remedy of common cluster level problems. To achieve this, we will use eksctl, cluster-autoscaler, external-dns, kube-prometheus (prometheus operator), node-problem-detector, draino, node-local-dns-cache, and a dashboard.

**Comment by InAnimaTe** [comment]
Sounds good to me (imma make some minor adjustments) @StevenACoffman I'll update materials

**Comment by StevenACoffman** [comment]
What was the minor adjustments again? I lost them.

**Comment by InAnimaTe** [comment]
This event has happened and was amazing. Events are in Todoist for getting resources back to people.
